let nameIsValid=!1;let emailIsValid=!1;let phoneNoIsValid=!1;let issueIsValid=!1;function validateName(){let name=document.getElementById("name").value.trim();let submissionIncompleteMsg=document.getElementById("submission-incomplete");let invalidNameMsg=document.getElementById("name-invalid");if(name===""){submissionIncompleteMsg.style.display="block";submissionIncompleteMsg.style.color="red";submissionIncompleteMsg.innerHTML="Please fill in all fields"
nameIsValid=!1;return!1}
let hasSymbol=!1;for(let i=0;i<name.length;i++){let character=name.charAt(i);let utf8ref=character.charCodeAt(0);if(character==" "){continue}
if(character=="-"){continue}
if(character=="'"){continue}
if(utf8ref>=65&&utf8ref<=90){continue}
if(utf8ref>=97&&utf8ref<=122){continue}
if(utf8ref>=192){continue}
hasSymbol=!0;break}
if(hasSymbol){invalidNameMsg.style.display="block";invalidNameMsg.style.color="red";invalidNameMsg.innerHTML="Names cannot contain numbers or symbols";nameIsValid=!1;return!1}else{invalidNameMsg.style.display="none";nameIsValid=!0;return!0}}
function validateEmail(){let email=document.getElementById("email").value.trim();let submissionIncompleteMsg=document.getElementById("submission-incomplete");let invalidEmailMsg=document.getElementById("invalid-email");let domainNames=["com","eu","ie","it","fr","co.uk","edu","gov"];let lastDotIndex=email.lastIndexOf(".");let domainName=email.substring(lastDotIndex+1);let domainNameCheck=!1;if(email===""){submissionIncompleteMsg.style.display="block";submissionIncompleteMsg.style.color="red";submissionIncompleteMsg.innerHTML="Please fill in all fields";emailIsValid=!1;return!1}else if(!email.includes("@")){invalidEmailMsg.style.display="block";invalidEmailMsg.style.color="red";invalidEmailMsg.innerHTML="An email must contain '@' symbol";emailIsValid=!1;return!1}else if(lastDotIndex==-1||lastDotIndex==email.length-1){invalidEmailMsg.style.display="block";invalidEmailMsg.style.color="red";invalidEmailMsg.innerHTML="An email must contain a domain.";emailIsValid=!1;return!1}
for(const domainName1 of domainNames){if(domainName1.toLowerCase()===domainName.toLowerCase()){domainNameCheck=!0;break}}
if(!domainNameCheck){invalidEmailMsg.style.display="block";invalidEmailMsg.style.color="red";invalidEmailMsg.innerHTML="The domain '"+domainName+"' is not supported. Please enter a different email address";emailIsValid=!1;return!1}else{emailIsValid=!0;return!0}}
function validatePhoneNo(){let phoneNo=document.getElementById("phone-number").value.trim();let submissionIncompleteMsg=document.getElementById("submission-incomplete");let invalidPhoneNo=document.getElementById("invalid-phone-number");let hasOnlyNumbers=!1;if(phoneNo===""){submissionIncompleteMsg.style.display="block";submissionIncompleteMsg.style.color="red";submissionIncompleteMsg.innerHTML="Please fill in all fields";phoneNoIsValid=!1;return!1}
for(let i=0;i<phoneNo.length;i++){let character=phoneNo.charAt(i);if(character<"0"||character>"9"){hasOtherThanNo=!0;break}}
if(hasOtherThanNo){invalidPhoneNo.style.display="block";invalidPhoneNo.style.color="red";invalidPhoneNo.innerHTML="A phone number must contain only numbers";hasOtherThanNo=!1;return!1}else{phoneNo=!0;return!0}}
function validateIssue(){let issue=document.getElementById("issue").value.trim();let submissionIncompleteMsg=document.getElementById("submission-incomplete");if(issue===""){submissionIncompleteMsg.style.display="block";submissionIncompleteMsg.style.color="red";submissionIncompleteMsg.innerHTML="Please fill in all fields"
issueIsValid=!1;return!1}else{issueIsValid=!0;return!0}}
function hideForm(){validateName();validateEmail();validatePhoneNo();validateIssue();if(nameIsValid&&emailIsValid&&phoneNoIsValid&&issueIsValid){document.getElementById("contact-us-form").style.display="none";document.getElementById("submission-incomplete").style.display="none";document.getElementById("submission-complete").style.display="block";document.getElementById("submission-complete").innerText="Thanks for contacting us, we'll get back to you promptly!"}
return!1}
